### ISSUE TITLE
Unable to use a module javascript file as a dependency - wrong MIME type error

### ISSUE THREAD

**Issue by daattali** [ramnathv/htmlwidgets#405]
In a widget's YAML file, when defining a JavaScript dependency, it doesn't seem to be possible to use a javascript file that's a module. The resulting page has a javascript console error message:

```
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

For a reproducible example: 

1. Use scaffoldWidget() to create a plain htmlwidget
2. Create the following javascript file as `inst/htmlwidgets/test.js`:

    ```
    export function foo() {
      alert("bar");
    }
    ```
3. Modify the default yaml file to:

    ```
    dependencies:
      - name: test
        version: 1.0.0
        src: htmlwidgets
        script:
          - src: test.js
            type: module
    ```
